import { Body, Controller, Get, Param, Patch, Post, UseGuards } from "@nestjs/common";
import { completeFixtureMaintenanceSchema, fixtureCalibrationPolicySchema, fixtureCalibrationRecordSchema, fixtureMaintenancePolicySchema, invalidateFixtureCalibrationSchema, scheduleFixtureMaintenanceSchema, updateFixtureCalibrationPolicySchema, updateFixtureMaintenancePolicySchema } from "@ahkmes/shared-types";
import { CurrentUser } from "../common/decorators/current-user.decorator"; import { RequireActionPermissions } from "../common/decorators/require-action-permission.decorator"; import { RequirePage } from "../common/decorators/require-page.decorator"; import { RequireProductModule } from "../common/decorators/require-product-module.decorator"; import { ActionPermissionsGuard } from "../common/guards/action-permissions.guard"; import { JwtAuthGuard } from "../common/guards/jwt-auth.guard"; import { PagesGuard } from "../common/guards/pages.guard"; import { RolesGuard } from "../common/guards/roles.guard"; import type { AuthUser } from "../common/types"; import { ZodValidationPipe } from "../common/zod-validation.pipe"; import { FixtureMaintenanceService } from "./fixture-maintenance.service";
@Controller("tooling/fixture-maintenance") @RequirePage("tooling") @RequireProductModule("MES_CNC_TOOLING") @UseGuards(JwtAuthGuard, RolesGuard, PagesGuard, ActionPermissionsGuard)
export class FixtureMaintenanceController {
  constructor(private readonly service: FixtureMaintenanceService) {}
  @Get("policies") @RequireActionPermissions("FIXTURE_READ") list(@CurrentUser() u: AuthUser) { return this.service.list(u.tenantId); }
  @Post("maintenance-policies") @RequireActionPermissions("FIXTURE_MAINT_MANAGE") createMaintenance(@CurrentUser() u: AuthUser, @Body(new ZodValidationPipe(fixtureMaintenancePolicySchema)) dto: any) { return this.service.createMaintenancePolicy(u.tenantId, dto); }
  @Patch("maintenance-policies/:id") @RequireActionPermissions("FIXTURE_MAINT_MANAGE") updateMaintenance(@CurrentUser() u: AuthUser, @Param("id") id: string, @Body(new ZodValidationPipe(updateFixtureMaintenancePolicySchema)) dto: any) { return this.service.updateMaintenancePolicy(u.tenantId, id, dto); }
  @Post("calibration-policies") @RequireActionPermissions("FIXTURE_MAINT_MANAGE") createCalibrationPolicy(@CurrentUser() u: AuthUser, @Body(new ZodValidationPipe(fixtureCalibrationPolicySchema)) dto: any) { return this.service.createCalibrationPolicy(u.tenantId, dto); }
  @Patch("calibration-policies/:id") @RequireActionPermissions("FIXTURE_MAINT_MANAGE") updateCalibrationPolicy(@CurrentUser() u: AuthUser, @Param("id") id: string, @Body(new ZodValidationPipe(updateFixtureCalibrationPolicySchema)) dto: any) { return this.service.updateCalibrationPolicy(u.tenantId, id, dto); }
  @Post("events") @RequireActionPermissions("FIXTURE_MAINT_MANAGE") schedule(@CurrentUser() u: AuthUser, @Body(new ZodValidationPipe(scheduleFixtureMaintenanceSchema)) dto: any) { return this.service.schedule(u.tenantId, u.userId, dto); }
  @Post("events/:id/start") @RequireActionPermissions("FIXTURE_MAINT_MANAGE") start(@CurrentUser() u: AuthUser, @Param("id") id: string, @Body(new ZodValidationPipe(updateFixtureMaintenancePolicySchema.pick({ version: true }))) dto: any) { return this.service.start(u.tenantId, u.userId, id, dto.version); }
  @Post("events/:id/complete") @RequireActionPermissions("FIXTURE_MAINT_MANAGE") complete(@CurrentUser() u: AuthUser, @Param("id") id: string, @Body(new ZodValidationPipe(completeFixtureMaintenanceSchema)) dto: any) { return this.service.complete(u.tenantId, u.userId, id, dto); }
  @Post("calibration-records") @RequireActionPermissions("FIXTURE_CALIBRATION_RECORD") calibration(@CurrentUser() u: AuthUser, @Body(new ZodValidationPipe(fixtureCalibrationRecordSchema)) dto: any) { return this.service.calibration(u.tenantId, u.userId, dto); }
  @Post("calibration-records/:id/invalidate") @RequireActionPermissions("FIXTURE_MAINT_OVERRIDE") invalidate(@CurrentUser() u: AuthUser, @Param("id") id: string, @Body(new ZodValidationPipe(invalidateFixtureCalibrationSchema)) dto: any) { return this.service.invalidateCalibration(u.tenantId, u.userId, id, dto); }
  @Get("fixtures/:id/history") @RequireActionPermissions("FIXTURE_READ") history(@CurrentUser() u: AuthUser, @Param("id") id: string) { return this.service.history(u.tenantId, id); }
  @Get("fixtures/:id/evaluation") @RequireActionPermissions("FIXTURE_READ") evaluate(@CurrentUser() u: AuthUser, @Param("id") id: string) { return this.service.evaluateForTenant(u.tenantId, id); }
  @Get("due") @RequireActionPermissions("FIXTURE_READ") due(@CurrentUser() u: AuthUser) { return this.service.due(u.tenantId); }
}
