import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CheckCircle2, Plus } from "lucide-react";
import { useState } from "react";
import { ApiError, apiGet, apiPatch, apiPost } from "../lib/api";
import { useAuth } from "../lib/auth";
import { Button, Label, Modal, Select, Table, Textarea } from "../components/ui";
import { useToast } from "../components/toast";

type Status = "DRAFT" | "RELEASED" | "OBSOLETE" | "LEGACY_UNVERIFIED";
interface Choice { id: string; name?: string; partNo?: string; revision?: string; status?: Status; }
interface Definition { id: string; status: Status; plant: { name: string }; part: { partNo: string; revision: string }; bomHeader: { revision: string; status: Status }; recipeHeader: { revision: string; status: Status }; }
const label: Record<Status, string> = { DRAFT: "Taslak", RELEASED: "Yayınlandı", OBSOLETE: "Geçersiz", LEGACY_UNVERIFIED: "Eski / doğrulanmamış" };

export function EngineeringMasterDataPage() {
  const qc = useQueryClient(); const toast = useToast(); const { user } = useAuth(); const canWrite = !!user && ["ADMIN", "PLANNER"].includes(user.role);
  const [open, setOpen] = useState(false); const [plantId, setPlantId] = useState(""); const [partId, setPartId] = useState(""); const [bomHeaderId, setBom] = useState(""); const [recipeHeaderId, setRouting] = useState(""); const [notes, setNotes] = useState("");
  const definitions = useQuery({ queryKey: ["/production-definitions"], queryFn: () => apiGet<Definition[]>("/production-definitions") });
  const plants = useQuery({ queryKey: ["/hierarchy/tree"], queryFn: () => apiGet<Choice[]>("/hierarchy/tree"), enabled: open });
  const parts = useQuery({ queryKey: ["/parts"], queryFn: () => apiGet<Choice[]>("/parts"), enabled: open });
  const boms = useQuery({ queryKey: ["/boms", partId], queryFn: () => apiGet<Choice[]>(`/boms?partId=${partId}`), enabled: open && !!partId });
  const routes = useQuery({ queryKey: ["/recipes", partId], queryFn: () => apiGet<Choice[]>(`/recipes?partId=${partId}`), enabled: open && !!partId });
  const save = useMutation({ mutationFn: () => apiPost("/production-definitions", { plantId, partId, bomHeaderId, recipeHeaderId, ...(notes ? { notes } : {}) }), onSuccess: () => { qc.invalidateQueries({ queryKey: ["/production-definitions"] }); setOpen(false); }, onError: (e) => toast(e instanceof ApiError ? ((e.body as { message?: string })?.message ?? "Kaydedilemedi") : "Kaydedilemedi", "error") });
  const release = useMutation({ mutationFn: (id: string) => apiPatch(`/production-definitions/${id}/status`, { status: "RELEASED" }), onSuccess: () => qc.invalidateQueries({ queryKey: ["/production-definitions"] }), onError: (e) => toast(e instanceof ApiError ? ((e.body as { message?: string })?.message ?? "Yayınlanamadı") : "Yayınlanamadı", "error") });
  return <div><div className="mb-6 flex items-center justify-between"><div><h1 className="text-2xl font-bold">Üretim Tanımları</h1><p className="mt-1 text-sm text-slate-500">Plant bazında yayınlanmış Part / BOM / rota eşlemesi.</p></div>{canWrite && <Button onClick={() => setOpen(true)}><Plus className="h-4 w-4" /> Yeni Tanım</Button>}</div><Table headers={["Plant", "Parça", "BOM", "Rota", "Durum", ""]}>{(definitions.data ?? []).map((row) => <tr key={row.id}><td className="px-4 py-3">{row.plant.name}</td><td className="px-4 py-3">{row.part.partNo} rev. {row.part.revision}</td><td className="px-4 py-3">{row.bomHeader.revision} · {label[row.bomHeader.status]}</td><td className="px-4 py-3">{row.recipeHeader.revision} · {label[row.recipeHeader.status]}</td><td className="px-4 py-3">{label[row.status]}</td><td className="px-4 py-3">{canWrite && row.status === "DRAFT" && <Button variant="outline" onClick={() => release.mutate(row.id)}><CheckCircle2 className="h-4 w-4" /> Yayınla</Button>}</td></tr>)}</Table><Modal open={open} title="Yeni Üretim Tanımı" onClose={() => setOpen(false)}><form onSubmit={(event) => { event.preventDefault(); save.mutate(); }} className="space-y-4"><div><Label>Plant</Label><Select required value={plantId} onChange={(e) => setPlantId(e.target.value)}><option value="">Seçin</option>{plants.data?.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</Select></div><div><Label>Parça revizyonu</Label><Select required value={partId} onChange={(e) => { setPartId(e.target.value); setBom(""); setRouting(""); }}><option value="">Seçin</option>{parts.data?.map((p) => <option key={p.id} value={p.id}>{p.partNo} rev. {p.revision} · {p.status ? label[p.status] : ""}</option>)}</Select></div><div><Label>BOM revizyonu</Label><Select required value={bomHeaderId} onChange={(e) => setBom(e.target.value)}><option value="">Seçin</option>{boms.data?.map((b) => <option key={b.id} value={b.id}>{b.revision} · {b.status ? label[b.status] : ""}</option>)}</Select></div><div><Label>Rota revizyonu</Label><Select required value={recipeHeaderId} onChange={(e) => setRouting(e.target.value)}><option value="">Seçin</option>{routes.data?.map((r) => <option key={r.id} value={r.id}>{r.revision} · {r.status ? label[r.status] : ""}</option>)}</Select></div><div><Label>Notlar</Label><Textarea value={notes} onChange={(e) => setNotes(e.target.value)} /></div><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => setOpen(false)}>Vazgeç</Button><Button type="submit">Kaydet</Button></div></form></Modal></div>;
}
